[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.23.0",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "radian>=0.6.13",
    "ruff>=0.9.9",
    "uv>=0.6.0",
]
